// .---------------- minute (0 - 59)
// | .-------------- hour (0 - 23)
// | | .------------ day of month (1 - 31)
// | | | .---------- month (1 - 12) OR jan,feb,mar ...
// | | | | .-------- day of week (0 - 6) (Sunday=0 or 7) OR sun,mon,tue ...
// | | | | |
// * * * * * command to be executed
CRON_SETTINGS = '''0 7-16 * * * % product=bingo;environment=test
5 7-16 * * * % product=bingo;environment=staging
10 7-16 * * * % product=bingo;environment=live
15 7-16 * * * % product=casino;environment=next
20 7-16 * * * % product=casino;environment=live
25 7-16 * * * % product=vegas;environment=test
30 7-16 * * * % product=vegas;environment=staging
35 7-16 * * * % product=vegas;environment=live'''

pipeline {
    agent {
        docker {
            args '--net host -u root:root'
            image 'mcr.microsoft.com/playwright:v1.39.0-jammy'
        }
    }

    environment {
        CI = 1
    }

    options {
        buildDiscarder(logRotator(
            daysToKeepStr: '7',         // history is only kept up to this days.
            numToKeepStr: '100',        // only this number of build logs are kept.
            artifactDaysToKeepStr: '7'  // artifacts are only kept up to this days.
        ))
        timeout(time: 5, unit: 'MINUTES')
    }

    parameters {
        string(name: 'branch', defaultValue: 'main', description: 'The branch to use for testing')
        choice(name: 'product', choices: ['bingo', 'casino', 'vegas', ''], description: 'The product to be tested')
        choice(name: 'environment', choices: ['live', 'staging', 'next', 'test', 'prod', 'preprod'], description: 'The environment to test')
    }

    triggers {
        parameterizedCron(CRON_SETTINGS)
    }

    stages {
        stage('initialize') {
            steps {
                script {
                    currentBuild.displayName = "Gaming UI Tests - ${params.product} ${params.environment} (${params.branch})"
                    addShortText(text: "branch: ${params.branch}")
                    addShortText(text: "product: ${params.product}")
                    addShortText(text: "environment: ${params.environment}")

                    git branch: 'main',
                        url: 'https://github.com/ngr05/gaming-ui-testing.git'
                        branch: params.branch
                }
                sh 'npm install'
            }
        }

        stage('run tests') {
            steps {
                script {
                    try {
                        sh "npm run test:${params.product}:${params.environment}"
                        def exitCode = sh returnStdout: true, script: 'echo $?'
                        if (exitCode.toInteger() > 0) {
                            throw new Exception('test failures found')
                        }
                    } catch (err) {
                        echo "Failed: ${err}"
                        currentBuild.result = 'FAILURE'
                    }
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts allowEmptyArchive: true, artifacts: 'test-results/**/*.*, playwright-report/**/*.*', followSymlinks: false
            sh 'rm -rf ./* ./.[a-zA-Z0-9]*'
        }

        // failure {
        //     script {
        //         slack.send([
        //             channel: '#gaming-ui-testing',
        //             username: 'Jenkins Runner',
        //             icon_emoji: ':failed:',
        //             text: "❌ Gaming UI Testing has failed! (Environment: ${params.environment}, Product: ${params.product})"
        //         ])
        //     }
        // }
    }
}
